extends: default

rules:
  line-length:
    max: 200
    level: warning
  comments:
    min-spaces-from-content: 1
  document-start: disable
  truthy:
    allowed-values: ['true', 'false', 'True', 'False']
    check-keys: false
  braces:
    max-spaces-inside: 1
    min-spaces-inside: 0
  brackets:
    max-spaces-inside: 1
    min-spaces-inside: 0
  colons:
    max-spaces-before: 0
    max-spaces-after: 1
  commas:
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: 1
  comments-indentation: disable
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false
  key-ordering: disable
  empty-values: disable
  quoted-strings: disable

# Ignore Helm template syntax
ignore: |
  helm/
  **/templates/**

